# Generated by Django 3.1.5 on 2021-07-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_system_monitor', '0003_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overview',
            options={'verbose_name': ' Overview', 'verbose_name_plural': ' Overview'},
        ),
    ]
