# Generated by Django 3.1.5 on 2021-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='name')),
                ('value', models.CharField(editable=False, max_length=512, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Env',
                'verbose_name_plural': 'Envs',
            },
        ),
    ]
